version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: aqua
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  login_app:
    build: .
    container_name: aqua-srv-login
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aqua
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app_network

  cadastro_app:
    build: .
    container_name: aqua-srv-cadastro
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aqua
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
