INSERT INTO cidade (nome_cidade, unidade_organizacional_id, ic_uso) VALUES
('Água Branca', 1, true),
('Anadia', 1, true),
('Arapiraca', 1, true),
('Atalaia', 1, true),
('Barra de Santo Antônio', 1, true),
('Barra de São Miguel', 1, true),
('Batalha', 1, true),
('Belém', 1, true),
('Belo Monte', 1, true),
('Boca da Mata', 1, true),
('Branquinha', 1, true),
('Cacimbinhas', 1, true),
('Cajueiro', 1, true),
('Campestre', 1, true),
('Campo Alegre', 1, true),
('Campo Grande', 1, true),
('Canapi', 1, true),
('Capela', 1, true),
('Carneiros', 1, true),
('Chã Preta', 1, true),
('Coité do Nóia', 1, true),
('Colônia Leopoldina', 1, true),
('Coqueiro Seco', 1, true),
('Coruripe', 1, true),
('Craíbas', 1, true),
('Delmiro Gouveia', 1, true),
('Dois Riachos', 1, true),
('Estrela de Alagoas', 1, true),
('Feira Grande', 1, true),
('Feliz Deserto', 1, true),
('Flexeiras', 1, true),
('Girau do Ponciano', 1, true),
('Ibateguara', 1, true),
('Igaci', 1, true),
('Igreja Nova', 1, true),
('Inhapi', 1, true),
('Jacaré dos Homens', 1, true),
('Jacuípe', 1, true),
('Japaratinga', 1, true),
('Jaramataia', 1, true),
('Jequiá da Praia', 1, true),
('Joaquim Gomes', 1, true),
('Jundiá', 1, true),
('Junqueiro', 1, true),
('Lagoa da Canoa', 1, true),
('Limoeiro de Anadia', 1, true),
('Maceió', 1, true),
('Major Isidoro', 1, true),
('Mar Vermelho', 1, true),
('Maragogi', 1, true),
('Maravilha', 1, true),
('Marechal Deodoro', 1, true),
('Maribondo', 1, true),
('Mata Grande', 1, true),
('Matriz de Camaragibe', 1, true),
('Messias', 1, true),
('Minador do Negrão', 1, true),
('Monteirópolis', 1, true),
('Murici', 1, true),
('Novo Lino', 1, true),
('Olho dÁgua das Flores', 1, true),
('Olho dÁgua do Casado', 1, true),
('Olho dÁgua Grande', 1, true),
('Olivença', 1, true),
('Ouro Branco', 1, true),
('Palestina', 1, true),
('Palmeira dos Índios', 1, true),
('Pão de Açúcar', 1, true),
('Pariconha', 1, true),
('Paripueira', 1, true),
('Passo de Camaragibe', 1, true),
('Paulo Jacinto', 1, true),
('Penedo', 1, true),
('Piaçabuçu', 1, true),
('Pilar', 1, true),
('Pindoba', 1, true),
('Piranhas', 1, true),
('Poço das Trincheiras', 1, true),
('Porto Calvo', 1, true),
('Porto de Pedras', 1, true),
('Porto Real do Colégio', 1, true),
('Quebrangulo', 1, true),
('Rio Largo', 1, true),
('Roteiro', 1, true),
('Santa Luzia do Norte', 1, true),
('Santana do Ipanema', 1, true),
('Santana do Mundaú', 1, true),
('São Brás', 1, true),
('São José da Laje', 1, true),
('São José da Tapera', 1, true),
('São Luís do Quitunde', 1, true),
('São Miguel dos Campos', 1, true),
('São Miguel dos Milagres', 1, true),
('São Sebastião', 1, true),
('Satuba', 1, true),
('Senador Rui Palmeira', 1, true),
('Tanque dArca', 1, true),
('Taquarana', 1, true),
('Teotônio Vilela', 1, true),
('Traipu', 1, true),
('União dos Palmares', 1, true),
('Viçosa', 1, true);
