name: aqua srv login main workflow
on: 
  workflow_dispatch:
    inputs:
      enable_dockerPrepare:
        type: boolean
        description: 'Habilitar Build DockerPrepare'
        required: false
        default: 'false'
      enable_pullDockerImage:
        type: boolean
        description: 'Habilitar pull do Docker Image'
        required: false
        default: 'false'
      enable_deployOnCloud:
        type: boolean
        description: 'Habilitar deploy no VPS'
        required: false
        default: 'false'

jobs:
  dockerPrepare:
    if: github.event.inputs.enable_dockerPrepare == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package code into Jar
        run: mvn clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-app
          path: target/api-0.0.1-SNAPSHOT.jar

  pullDockerImage:
    if: github.event.inputs.enable_pullDockerImage == true
    runs-on: ubuntu-latest
    needs: dockerPrepare  # Ensures this job runs AFTER dockerPrepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log directory tree
        run: |
          sudo apt-get update && sudo apt-get install -y tree
          tree -L 3

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aqua-one-login:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aqua-one-login:latest
  deployOnCloud:
    if: github.event.inputs.enable_deployOnCloud == true
    runs-on: ubuntu-latest
    needs: pullDockerImage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar o SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copiando arquivos para servidos
        run: |
          scp -r ./kubernetes ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/k8s/login-srv

      - name: Executando Helm
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /home/k8s/login-srv && helm package . "

