name: aqua srv login main workflow
on: workflow_dispatch
jobs:
  dockerPrepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get to the repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Package code into Jar
        run: mvn clean package -DsKipTests

      - name: Try to build
        uses: actions/upload-artifact@v4
        with:
          name: spring-app
          path: target/api-0.0.1-SNAPSHOT.jar
          
  pullDockerImage:
    runs-on: ubuntu-latest
    needs: dockerPrepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-app
          path: target
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aqua-one-login:latest .
  
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aqua-one-login:latest
